# Autogenerated wrapper script for Geant4_jll for aarch64-apple-darwin
export data_dir, libG4Analysis, libG4CLHEP, libG4Digits, libG4ErrorPropagation, libG4Event, libG4FR, libG4GDML, libG4GeomText, libG4Geometry, libG4Global, libG4Graphics, libG4Intercoms, libG4Interfaces, libG4MCTruth, libG4Material, libG4Mocren, libG4Modeling, libG4ParModels, libG4Particles, libG4PhysicsLists, libG4Processes, libG4Ptl, libG4RayTracer, libG4Readout, libG4Run, libG4ToolsSG, libG4Track, libG4Tracking, libG4Tree, libG4VRML, libG4VisHepRep, libG4visManagement

using Expat_jll
using Xorg_libXmu_jll
using Libglvnd_jll
using Xerces_jll
JLLWrappers.@generate_wrapper_header("Geant4")
JLLWrappers.@declare_file_product(data_dir)
JLLWrappers.@declare_library_product(libG4Analysis, "@rpath/libG4analysis.dylib")
JLLWrappers.@declare_library_product(libG4CLHEP, "@rpath/libG4clhep.dylib")
JLLWrappers.@declare_library_product(libG4Digits, "@rpath/libG4digits_hits.dylib")
JLLWrappers.@declare_library_product(libG4ErrorPropagation, "@rpath/libG4error_propagation.dylib")
JLLWrappers.@declare_library_product(libG4Event, "@rpath/libG4event.dylib")
JLLWrappers.@declare_library_product(libG4FR, "@rpath/libG4FR.dylib")
JLLWrappers.@declare_library_product(libG4GDML, "@rpath/libG4gdml.dylib")
JLLWrappers.@declare_library_product(libG4GeomText, "@rpath/libG4geomtext.dylib")
JLLWrappers.@declare_library_product(libG4Geometry, "@rpath/libG4geometry.dylib")
JLLWrappers.@declare_library_product(libG4Global, "@rpath/libG4global.dylib")
JLLWrappers.@declare_library_product(libG4Graphics, "@rpath/libG4graphics_reps.dylib")
JLLWrappers.@declare_library_product(libG4Intercoms, "@rpath/libG4intercoms.dylib")
JLLWrappers.@declare_library_product(libG4Interfaces, "@rpath/libG4interfaces.dylib")
JLLWrappers.@declare_library_product(libG4MCTruth, "@rpath/libG4mctruth.dylib")
JLLWrappers.@declare_library_product(libG4Material, "@rpath/libG4materials.dylib")
JLLWrappers.@declare_library_product(libG4Mocren, "@rpath/libG4GMocren.dylib")
JLLWrappers.@declare_library_product(libG4Modeling, "@rpath/libG4modeling.dylib")
JLLWrappers.@declare_library_product(libG4ParModels, "@rpath/libG4parmodels.dylib")
JLLWrappers.@declare_library_product(libG4Particles, "@rpath/libG4particles.dylib")
JLLWrappers.@declare_library_product(libG4PhysicsLists, "@rpath/libG4physicslists.dylib")
JLLWrappers.@declare_library_product(libG4Processes, "@rpath/libG4processes.dylib")
JLLWrappers.@declare_library_product(libG4Ptl, "@rpath/libG4ptl.3.dylib")
JLLWrappers.@declare_library_product(libG4RayTracer, "@rpath/libG4RayTracer.dylib")
JLLWrappers.@declare_library_product(libG4Readout, "@rpath/libG4readout.dylib")
JLLWrappers.@declare_library_product(libG4Run, "@rpath/libG4run.dylib")
JLLWrappers.@declare_library_product(libG4ToolsSG, "@rpath/libG4ToolsSG.dylib")
JLLWrappers.@declare_library_product(libG4Track, "@rpath/libG4track.dylib")
JLLWrappers.@declare_library_product(libG4Tracking, "@rpath/libG4tracking.dylib")
JLLWrappers.@declare_library_product(libG4Tree, "@rpath/libG4Tree.dylib")
JLLWrappers.@declare_library_product(libG4VRML, "@rpath/libG4VRML.dylib")
JLLWrappers.@declare_library_product(libG4VisHepRep, "@rpath/libG4visHepRep.dylib")
JLLWrappers.@declare_library_product(libG4visManagement, "@rpath/libG4vis_management.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Expat_jll, Xorg_libXmu_jll, Libglvnd_jll, Xerces_jll)
    JLLWrappers.@init_file_product(
        data_dir,
        "share/Geant4/data",
    )

    JLLWrappers.@init_library_product(
        libG4Analysis,
        "lib/libG4analysis.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4CLHEP,
        "lib/libG4clhep.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Digits,
        "lib/libG4digits_hits.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4ErrorPropagation,
        "lib/libG4error_propagation.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Event,
        "lib/libG4event.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4FR,
        "lib/libG4FR.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4GDML,
        "lib/libG4gdml.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4GeomText,
        "lib/libG4geomtext.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Geometry,
        "lib/libG4geometry.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Global,
        "lib/libG4global.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Graphics,
        "lib/libG4graphics_reps.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Intercoms,
        "lib/libG4intercoms.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Interfaces,
        "lib/libG4interfaces.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4MCTruth,
        "lib/libG4mctruth.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Material,
        "lib/libG4materials.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Mocren,
        "lib/libG4GMocren.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Modeling,
        "lib/libG4modeling.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4ParModels,
        "lib/libG4parmodels.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Particles,
        "lib/libG4particles.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4PhysicsLists,
        "lib/libG4physicslists.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Processes,
        "lib/libG4processes.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Ptl,
        "lib/libG4ptl.3.0.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4RayTracer,
        "lib/libG4RayTracer.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Readout,
        "lib/libG4readout.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Run,
        "lib/libG4run.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4ToolsSG,
        "lib/libG4ToolsSG.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Track,
        "lib/libG4track.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Tracking,
        "lib/libG4tracking.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Tree,
        "lib/libG4Tree.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4VRML,
        "lib/libG4VRML.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4VisHepRep,
        "lib/libG4visHepRep.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4visManagement,
        "lib/libG4vis_management.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
