# Autogenerated wrapper script for Geant4_jll for x86_64-w64-mingw32-cxx03
export data_dir, libG4Analysis, libG4CLHEP, libG4Digits, libG4ErrorPropagation, libG4Event, libG4FR, libG4GDML, libG4GeomText, libG4Geometry, libG4Global, libG4Graphics, libG4Intercoms, libG4Interfaces, libG4MCTruth, libG4Material, libG4Mocren, libG4Modeling, libG4ParModels, libG4Particles, libG4PhysicsLists, libG4Processes, libG4Ptl, libG4RayTracer, libG4Readout, libG4Run, libG4ToolsSG, libG4Track, libG4Tracking, libG4Tree, libG4VRML, libG4VisHepRep, libG4visManagement

using Expat_jll
using Xorg_libXmu_jll
using Libglvnd_jll
using Xerces_jll
JLLWrappers.@generate_wrapper_header("Geant4")
JLLWrappers.@declare_file_product(data_dir)
JLLWrappers.@declare_library_product(libG4Analysis, "libG4analysis.dll")
JLLWrappers.@declare_library_product(libG4CLHEP, "libG4clhep.dll")
JLLWrappers.@declare_library_product(libG4Digits, "libG4digits_hits.dll")
JLLWrappers.@declare_library_product(libG4ErrorPropagation, "libG4error_propagation.dll")
JLLWrappers.@declare_library_product(libG4Event, "libG4event.dll")
JLLWrappers.@declare_library_product(libG4FR, "libG4FR.dll")
JLLWrappers.@declare_library_product(libG4GDML, "libG4gdml.dll")
JLLWrappers.@declare_library_product(libG4GeomText, "libG4geomtext.dll")
JLLWrappers.@declare_library_product(libG4Geometry, "libG4geometry.dll")
JLLWrappers.@declare_library_product(libG4Global, "libG4global.dll")
JLLWrappers.@declare_library_product(libG4Graphics, "libG4graphics_reps.dll")
JLLWrappers.@declare_library_product(libG4Intercoms, "libG4intercoms.dll")
JLLWrappers.@declare_library_product(libG4Interfaces, "libG4interfaces.dll")
JLLWrappers.@declare_library_product(libG4MCTruth, "libG4mctruth.dll")
JLLWrappers.@declare_library_product(libG4Material, "libG4materials.dll")
JLLWrappers.@declare_library_product(libG4Mocren, "libG4GMocren.dll")
JLLWrappers.@declare_library_product(libG4Modeling, "libG4modeling.dll")
JLLWrappers.@declare_library_product(libG4ParModels, "libG4parmodels.dll")
JLLWrappers.@declare_library_product(libG4Particles, "libG4particles.dll")
JLLWrappers.@declare_library_product(libG4PhysicsLists, "libG4physicslists.dll")
JLLWrappers.@declare_library_product(libG4Processes, "libG4processes.dll")
JLLWrappers.@declare_library_product(libG4Ptl, "libG4ptl.dll")
JLLWrappers.@declare_library_product(libG4RayTracer, "libG4RayTracer.dll")
JLLWrappers.@declare_library_product(libG4Readout, "libG4readout.dll")
JLLWrappers.@declare_library_product(libG4Run, "libG4run.dll")
JLLWrappers.@declare_library_product(libG4ToolsSG, "libG4ToolsSG.dll")
JLLWrappers.@declare_library_product(libG4Track, "libG4track.dll")
JLLWrappers.@declare_library_product(libG4Tracking, "libG4tracking.dll")
JLLWrappers.@declare_library_product(libG4Tree, "libG4Tree.dll")
JLLWrappers.@declare_library_product(libG4VRML, "libG4VRML.dll")
JLLWrappers.@declare_library_product(libG4VisHepRep, "libG4visHepRep.dll")
JLLWrappers.@declare_library_product(libG4visManagement, "libG4vis_management.dll")
function __init__()
    JLLWrappers.@generate_init_header(Expat_jll, Xorg_libXmu_jll, Libglvnd_jll, Xerces_jll)
    JLLWrappers.@init_file_product(
        data_dir,
        "share\\Geant4\\data",
    )

    JLLWrappers.@init_library_product(
        libG4Analysis,
        "bin\\libG4analysis.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4CLHEP,
        "bin\\libG4clhep.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Digits,
        "bin\\libG4digits_hits.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4ErrorPropagation,
        "bin\\libG4error_propagation.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Event,
        "bin\\libG4event.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4FR,
        "bin\\libG4FR.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4GDML,
        "bin\\libG4gdml.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4GeomText,
        "bin\\libG4geomtext.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Geometry,
        "bin\\libG4geometry.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Global,
        "bin\\libG4global.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Graphics,
        "bin\\libG4graphics_reps.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Intercoms,
        "bin\\libG4intercoms.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Interfaces,
        "bin\\libG4interfaces.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4MCTruth,
        "bin\\libG4mctruth.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Material,
        "bin\\libG4materials.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Mocren,
        "bin\\libG4GMocren.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Modeling,
        "bin\\libG4modeling.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4ParModels,
        "bin\\libG4parmodels.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Particles,
        "bin\\libG4particles.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4PhysicsLists,
        "bin\\libG4physicslists.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Processes,
        "bin\\libG4processes.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Ptl,
        "bin\\libG4ptl.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4RayTracer,
        "bin\\libG4RayTracer.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Readout,
        "bin\\libG4readout.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Run,
        "bin\\libG4run.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4ToolsSG,
        "bin\\libG4ToolsSG.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Track,
        "bin\\libG4track.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Tracking,
        "bin\\libG4tracking.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4Tree,
        "bin\\libG4Tree.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4VRML,
        "bin\\libG4VRML.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4VisHepRep,
        "bin\\libG4visHepRep.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libG4visManagement,
        "bin\\libG4vis_management.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
